project:
  type: website
  output-dir: build

website:
  title: "LI Yifeng's Research"
  site-url: "https://research.yifen9.li"
  description: "LI Yifeng's Research"
  repo-url: https://github.com/yifen9/research
  favicon: icon.png
  twitter-card: true
  page-navigation: true
  bread-crumbs: true
  open-graph: true
  llms-txt: true
  navbar:
    logo: icon.png
    title: LI Yifeng
    search: true
    pinned: true
    left:
      - text: Blog
        href: https://blog.yifen9.li
      - text: Research
        href: https://research.yifen9.li
      - text: About
        href: https://yifen9.li
    right:
      - icon: person
        href: https://yifen9.li
      - icon: github
        href: https://github.com/yifen9/research
      - icon: rss
        href: index.xml
      
  page-footer:
    left: |
      <img src="https://counter.clarelab.moe/@www-yifeng-li?name=www-yifeng-li&theme=sketch-1&padding=8&offset=0&align=top&scale=0.2&pixelated=1&darkmode=0" alt=":counter" loading="lazy"/>
    center: |
      © {{< now year >}} <a href="https://yifen9.li">LI Yifeng</a>
    right:
      - text: "Powered by"
      - text: "GitHub"
        href: https://github.com
      - text: "&"
      - text: "Quarto"
        href: https://quarto.org

format:
  html:
    css:
      - styles.css
    theme: [cosmo, theme.scss]
    toc: true
    toc-depth: 16
    code-block-bg: true
    code-block-border-left: false
    code-copy: true
    code-line-numbers: true
    code-overflow: wrap
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
