RUN bun install -g \
        @biomejs/biome \
        pyright \
        typescript \
        typescript-language-server \
        vscode-langservers-extracted \
        yaml-language-server \
    && biome --version \
    && pyright --version \
    && yaml-language-server --version
