config:
  rank:
    - yaml
    - toml
    - json

  yaml:
    main: true

  toml:
    allow: true

  json:
    api: true
    hand: false
    allow:
      - devcontainer.json
      - opencode.json
      - package.json
      - tsconfig.json
