name:
  case:
    python: snake
    file: kebab
    dir: kebab
    yaml: snake

  number:
    dir: single
    file: single
    module: single

  word:
    source: config/rule/word
    strict: true

  allow:
    - .git
    - .github
    - .devcontainer
    - README.md
    - LICENSE
    - Dockerfile
    - _manifest.md
    - _meta.json
    - __init__.py
    - SOURCE.yaml
    - justfile
    - pyproject.toml
    - opencode.json
    - devcontainer.json
    - _quarto.yaml
